export default {
    LAYOUT_LEFT_SIDEBAR_TOGGLE: "LAYOUT_LEFT_SIDEBAR_TOGGLE",
    LAYOUT_LEFT_SIDEBAR_SHOW: "LAYOUT_LEFT_SIDEBAR_SHOW",
    LAYOUT_LEFT_SIDEBAR_HIDE: "LAYOUT_LEFT_SIDEBAR_HIDE",
    LAYOUT_RIGHT_SIDEBAR_TOGGLE: "LAYOUT_RIGHT_SIDEBAR_TOGGLE",
    LAYOUT_RIGHT_SIDEBAR_SHOW: "LAYOUT_RIGHT_SIDEBAR_SHOW",
    LAYOUT_RIGHT_SIDEBAR_HIDE: "LAYOUT_RIGHT_SIDEBAR_HIDE",

    LAYOUT_WINDOW_RESIZE: "LAYOUT_WINDOW_RESIZE",
};
