export default {
    CALL_RESPONSE_CONTACTING: `RESPONSE_CONTACTING`,
    CALL_RESPONSE_PEER_ID: `CALL_RESPONSE_PEER_ID`,
    CALL_REQUEST_CALL: `CALL_REQUEST_CALL`,
    CALL_REJECT_CALL: `CALL_REJECT_CALL`,
    CALL_ANSWER_CALL: `CALL_ANSWER_CALL`,
    CALL_CLEAR: `CALL_CLEAR`,
};