export const CONTACT_CREATE_START = 'CONTACT_CREATE_START';
export const CONTACT_CREATE_SUCCESS = 'CONTACT_CREATE_SUCCESS';
export const CONTACT_CREATE_ERROR = 'CONTACT_CREATE_ERROR';

export const CONTACT_GET_START = 'CONTACT_GET_START';
export const CONTACT_GET_SUCCESS = 'CONTACT_GET_SUCCESS';
export const CONTACT_GET_ERROR = 'CONTACT_GET_ERROR';

export const REQUEST_GET_START = 'REQUEST_GET_START';
export const REQUEST_GET_SUCCESS = 'REQUEST_GET_SUCCESS';
export const REQUEST_GET_ERROR = 'REQUEST_GET_ERROR';

export const REQUEST_SENT_GET_START = 'REQUEST_SENT_GET_START';
export const REQUEST_SENT_GET_SUCCESS = 'REQUEST_SENT_GET_SUCCESS';
export const REQUEST_SENT_GET_ERROR = 'REQUEST_SENT_GET_ERROR';


export const CONTACT_UPDATE_START = 'CONTACT_UPDATE_START';
export const CONTACT_UPDATE_SUCCESS = 'CONTACT_UPDATE_SUCCESS';
export const CONTACT_UPDATE_ERROR = 'CONTACT_UPDATE_ERROR';

export const CONTACT_DESTROY_START = 'CONTACT_DESTROY_START';
export const CONTACT_DESTROY_SUCCESS = 'CONTACT_DESTROY_SUCCESS';
export const CONTACT_DESTROY_ERROR = 'CONTACT_DESTROY_ERROR';

export const REQUEST_DESTROY_START = 'REQUEST_DESTROY_START';
export const REQUEST_DESTROY_SUCCESS = 'REQUEST_DESTROY_SUCCESS';
export const REQUEST_DESTROY_ERROR = 'REQUEST_DESTROY_ERROR';

export const REQUEST_SENT_DESTROY_START = 'REQUEST_SENT_DESTROY_START';
export const REQUEST_SENT_DESTROY_SUCCESS = 'REQUEST_SENT_DESTROY_SUCCESS';
export const REQUEST_SENT_DESTROY_ERROR = 'REQUEST_SENT_DESTROY_ERROR';

export const CONTACT_FIND_START = 'CONTACT_FIND_START';
export const CONTACT_FIND_SUCCESS = 'CONTACT_FIND_SUCCESS';
export const CONTACT_FIND_ERROR = 'CONTACT_FIND_ERROR';

export const CONTACT_REQUEST_ADDED = 'CONTACT_REQUEST_ADDED';
export const CONTACT_REQUEST_ADD = 'CONTACT_REQUEST_ADD';

