export const USER_ADD_CONTACT_START = `USER_ADD_CONTACT_START`;
export const USER_ADD_CONTACT_SUCCESS = `USER_ADD_CONTACT_SUCCESS`;
export const USER_ADD_CONTACT_ERROR = `USER_ADD_CONTACT_ERROR`;

export const USER_GET_START = `USER_GET_START`;
export const USER_GET_SUCCESS = `USER_GET_SUCCESS`;
export const USER_GET_ERROR = `USER_GET_ERROR`;

export const USER_GET_CURRENT_START = `USER_GET_CURRENT_START`;
export const USER_GET_CURRENT_SUCCESS = `USER_GET_CURRENT_SUCCESS`;
export const USER_GET_CURRENT_ERROR = `USER_GET_CURRENT_ERROR`;

export const USER_UPDATE_CONTACT_START = `USER_UPDATE_CONTACT_START`;
export const USER_UPDATE_CONTACT_SUCCESS = `USER_UPDATE_CONTACT_SUCCESS`;
export const USER_UPDATE_CONTACT_ERROR = `USER_UPDATE_CONTACT_ERROR`;

export const USER_UPDATE_START = `USER_UPDATE_START`;
export const USER_UPDATE_SUCCESS = `USER_UPDATE_SUCCESS`;
export const USER_UPDATE_ERROR = `USER_UPDATE_ERROR`;

export const USER_REMOVE_CONTACT_START = `USER_REMOVE_CONTACT_START`;
export const USER_REMOVE_CONTACT_SUCCESS = `USER_REMOVE_CONTACT_SUCCESS`;
export const USER_REMOVE_CONTACT_ERROR = `USER_REMOVE_CONTACT_ERROR`;

export const USER_FIND_START = `USER_FIND_START`;
export const USER_FIND_SUCCESS = `USER_FIND_SUCCESS`;
export const USER_FIND_ERROR = `USER_FIND_ERROR`;

export const USER_CHANGE_AVATAR = `USER_CHANGE_AVATAR`;

