
export const SIGNIN_START = `SIGNIN_START`;
export const SIGNIN_SUCCESS = `SIGNIN_SUCCESS`;
export const SIGNIN_ERROR = `SIGNIN_ERROR`;

export const SIGNUP_START = `SIGNUP_START`;
export const SIGNUP_SUCCESS = `SIGNUP_SUCCESS`;
export const SIGNUP_ERROR = `SIGNUP_ERROR`;

export const ERROR_MESSAGE_CLEAR = `SIGNIN_ERROR_MESSAGE_CLEAR`;
