
export const SIGNIN_INIT_LOADING_DONE = `SIGNIN_INIT_LOADING_DONE`;

export const SIGNIN_START = `SIGNIN_START`;
export const SIGNIN_SUCCESS = `SIGNIN_SUCCESS`;
export const SIGNIN_ERROR = `SIGNIN_ERROR`;

export const SIGNUP_START = `SIGNUP_START`;
export const SIGNUP_SUCCESS = `SIGNUP_SUCCESS`;
export const SIGNUP_ERROR = `SIGNUP_ERROR`;

export const SEND_RESET_PASSWORD_START = `SEND_RESET_PASSWORD_START`;
export const SEND_RESET_PASSWORD_SUCCESS = `SEND_RESET_PASSWORD_SUCCESS`;
export const SEND_RESET_PASSWORD_ERROR = `SEND_RESET_PASSWORD_ERROR`;

export const CHANGE_PASSWORD_START = `CHANGE_PASSWORD_START`;
export const CHANGE_PASSWORD_SUCCESS = `CHANGE_PASSWORD_SUCCESS`;
export const CHANGE_PASSWORD_ERROR = `CHANGE_PASSWORD_ERROR`;

export const ERROR_MESSAGE_CLEAR = `SIGNIN_ERROR_MESSAGE_CLEAR`;
